[im]
class = ['zoom', 'KotatogramDesktop', 'Slack', 'TelegramDesktop', 'Skype']
geom = '547x1173+1373+0'
keybind_default_toggle = ['Mod4+e']

[im.tel]
prog = 'kotatogram-desktop'
class = ['KotatogramDesktop']
keybind_spec_subtag = ['t']

[1password]
prog = '1password'
instance = '1password'
geom = '845x419+1070+725'
keybind_default_toggle = ['Mod4+Control+p']

[ncmpcpp]
instance = ['ncmpcpp', 'cool-retro-term']
geom = '1133x466+395+443'
spawn = 'ncmpcpp'
keybind_default_toggle = ['Mod4+f']

[neomutt]
class = ['mutterfox']
instance = ['mutterfox', 'neomutt']
geom = '1835x1114+52+0'
spawn = 'neomutt'
keybind_default_toggle = ['Mod4+n']

[teardrop]
instance = ['teardrop']
geom = '1920x803+0+0'
spawn = 'teardrop'
keybind_default_toggle = ['Mod4+d']

[webcam]
instance = ['webcam']
geom = '1234x771+667+363'
prog = '~/bin/webcam'
keybind_spec_toggle = ['w']

[discord]
prog = 'discord'
class = ['discord']
geom = '944x1036+974+127'
keybind_default_toggle = ['Mod4+v']

[transients]
match_all = ['True']
role = ['GtkFileChooserDialog', 'Organizer', 'Manager']
geom = '1412x429+2+7'
