[project]
name="negwm"
description="negwm - brings a lot of unique UX features inspired by notion/ion3"
authors=[
    {name = "Neg", email = "serg.zorg@gmail.com"},
]
license="LGPL-3.0"
readme={file="README.md", "content-type"="text/markdown"}
requires-python=">=3.11"
packages=[
    {include='negwm/__main__.py'},
    {include='negwm/*.py'},
    {include='negwm/lib/*.py'},
    {include='negwm/bin/create_cfg'},
    {include='negwm/modules/*.py'},
]
keywords=["negwm", "i3", "i3ipc"]
dependencies=[
    "asyncinotify",
    "docopt",
    "ewmh",
    "i3ipc",
    "inotipy",
    "promptx",
    "psutil",
    "python3-xlib",
    "rich",
    "ruamel-yaml",
    "systemd",
    "Xlib",
]
dynamic=["version"]

[tool.hatch.version]
source = "vcs"

[project.urls]
homepage="https://github.com/neg-serg/negwm"
repository="https://github.com/neg-serg/negwm"

[project.scripts]
negwm="negwm.main:NegWM.main"

[build-system]
requires=["hatchling>=1.17.1", "hatch-vcs>=0.3.0"]
build-backend="hatchling.build"
