[tool.poetry]
name = "negi3wm"
version = "0.9.0"
description = "negi3wm - brings a lot of unique UX features inspired by notion/ion3"
authors = ["Neg <serg.zorg@gmail.com>"]
license = "LGPL-3.0 License"
readme = "README.md"
homepage = "https://github.com/neg-serg/negi3wm"
repository = "https://github.com/neg-serg/negi3wm"
include = ["README.md", "Makefile", "LICENSE", "src", "lib", "cfg", "bin"]

[tool.poetry.dependencies]
python = "^3.9"
asyncinotify = "^2.0.2"
docopt = "^0.6.2"
ewmh = "^0.1.6"
i3ipc = "^2.2.1"
inotipy = "^0.1.1"
pulsectl = "^21.9.1"
python3-xlib = "^0.15"
yamlloader = "^1.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
