[tool.poetry]
name = "negwm"
version = "0.9.1"
description = "negwm - brings a lot of unique UX features inspired by notion/ion3"
authors = ["Neg <serg.zorg@gmail.com>"]
license = "LGPL-3.0 License"
readme = "README.md"
homepage = "https://github.com/neg-serg/negwm"
repository = "https://github.com/neg-serg/negwm"
include = [
    'LICENSE',
    'README-en.md',
    'README.md',
    'bin',
    'cfg',
    'lib',
    'modules',
    'negwm.py',
]

[tool.poetry.dependencies]
Xlib = '*'
asyncinotify = '*'
docopt = '*'
ewmh = '*'
i3ipc = '*'
inotipy = '*'
psutil = '*'
pulsectl = '*'
python = '*'
python3-xlib = '*'
rich = '*'
xdg = '*'
yamlloader = '*'

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
