.TH i3-persist 1 "MARCH 2018" 1.0.3 "User Manuals"

.SH NAME
i3-persist \- extends i3 window management with persistent containers



.SH SYNOPSIS
.SY i3-persist
.OP \-v|--version
.OP \-h|--help
.B lock|unlock|toggle|kill
\fIid\fP
.YS

.SH DESCRIPTION
.B i3-persist
closes a container or switches its state from closable to persistent.

Using the featured set of commands, containers can be marked so as to prevent their careless closing. A custom kill command is made available as a plug-in substitute for
.B i3-msg kill.
If a container is marked as persistent, attempted closing of the container through the command will have no effect.

.SH SUBCOMMANDS

.TP
.B lock
Mark the container as persistent. Prevents subsequent closes.
.TP

.B unlock
Mark the container as closable. Allows the container to be closed.

.TP
.B toggle
Toggle the container between the two states.

.TP
.B kill
Close the container unless either the container or any of its descending containers are locked. Otherwise, don't do anything.

.RE
By default,
.B i3-persist
will operate on the currently focused container. For scripting purposes, it is possible to pass a
.B con\_id
to all methods.  


.SH AUTHOR
.MT igorsowinski@gmail@\:gmail.com
Igor Sowinski
.ME

.SH COPYRIGHT
Copyright \[u00A9] 2018 Igor Sowinski.  Licensed under the 3-clause BSD license.
